server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    # Apenas SPA. O nginx do HOST faz o proxy de /api → access-api:8000
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
